//! UTC, TT and UT1 conversion and IAU 2006 mean sidereal time.
//!
//! `ut1_utc.bin`, generated by `tools/sidera_ut1.py`, stores monthly Delta T
//! knots derived from the official IERS 20u24 C04 UT1-UTC series, plus its
//! final daily value. Linear interpolation
//! reproduces the 2000-01-01 through 2026-08-25 daily source rows with a worst
//! residual of 0.0058 s. After that final observation SIDERA holds UT1-UTC at
//! +0.0070542 s through its 2050 limit. This constant-DUT1 scenario preserves
//! the frozen Horizons oracle, but has no claimed future Earth-rotation error
//! bound. Historical leap seconds are explicit; future UTC assumes no new
//! leap second after the last published entry and is a declared limitation.

use anyhow::{bail, ensure, Result};

const UT1_C04: &[u8] = include_bytes!("../../data/sidera/ut1_utc.bin");
const JD_J2000: f64 = 2_451_545.0;
const ARCSEC_TO_RAD: f64 = std::f64::consts::PI / 648_000.0;
const MJD_OFFSET: f64 = 2_400_000.5;
const UT1_HEADER_BYTES: usize = 16;
const UT1_TICKS_PER_SECOND: f64 = 10_000_000.0;

#[derive(Clone, Copy, Debug)]
struct Ut1History {
    start_year: i32,
    monthly_count: usize,
    history_end_jd: f64,
    predicted_dut1: f64,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct UtcDateTime {
    pub year: i32,
    pub month: u32,
    pub day: u32,
    pub hour: u32,
    pub minute: u32,
    pub second: f64,
}

impl UtcDateTime {
    pub fn parse(value: &str) -> Result<Self> {
        let value = value
            .strip_suffix('Z')
            .ok_or_else(|| anyhow::anyhow!("UTC datetime must end in Z"))?;
        let (date, clock) = value
            .split_once('T')
            .ok_or_else(|| anyhow::anyhow!("UTC datetime must contain T"))?;
        let mut date = date.split('-');
        let year: i32 = date
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing year"))?
            .parse()?;
        let month: u32 = date
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing month"))?
            .parse()?;
        let day: u32 = date
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing day"))?
            .parse()?;
        ensure!(date.next().is_none(), "extra UTC date field");
        let mut clock = clock.split(':');
        let hour: u32 = clock
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing hour"))?
            .parse()?;
        let minute: u32 = clock
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing minute"))?
            .parse()?;
        let second: f64 = clock
            .next()
            .ok_or_else(|| anyhow::anyhow!("missing second"))?
            .parse()?;
        ensure!(clock.next().is_none(), "extra UTC clock field");
        let result = Self {
            year,
            month,
            day,
            hour,
            minute,
            second,
        };
        result.validate()?;
        Ok(result)
    }

    pub fn validate(&self) -> Result<()> {
        ensure!(
            (2000..=2050).contains(&self.year),
            "SIDERA supports UTC years 2000–2050"
        );
        ensure!((1..=12).contains(&self.month), "invalid UTC month");
        let days = days_in_month(self.year, self.month);
        ensure!((1..=days).contains(&self.day), "invalid UTC day");
        ensure!(
            self.hour < 24
                && self.minute < 60
                && self.second.is_finite()
                && (0.0..60.0).contains(&self.second),
            "invalid UTC clock time"
        );
        Ok(())
    }

    pub fn jd_utc(&self) -> Result<f64> {
        self.validate()?;
        Ok(julian_day(self.year, self.month, self.day)
            + (self.hour as f64 * 3600.0 + self.minute as f64 * 60.0 + self.second) / 86_400.0)
    }

    pub fn jd_tt(&self) -> Result<f64> {
        Ok(self.jd_utc()? + (tai_minus_utc(*self) + 32.184) / 86_400.0)
    }

    pub fn delta_t_seconds(&self) -> Result<f64> {
        self.validate()?;
        let history = ut1_history()?;
        let jd_utc = self.jd_utc()?;
        if jd_utc <= history.history_end_jd {
            historical_delta_t(*self, history, jd_utc)
        } else {
            Ok(tai_minus_utc(*self) + 32.184 - history.predicted_dut1)
        }
    }

    fn ut1_minus_utc_seconds(&self) -> Result<f64> {
        self.validate()?;
        let history = ut1_history()?;
        let jd_utc = self.jd_utc()?;
        if jd_utc <= history.history_end_jd {
            Ok(tai_minus_utc(*self) + 32.184 - historical_delta_t(*self, history, jd_utc)?)
        } else {
            Ok(history.predicted_dut1)
        }
    }

    pub fn jd_ut1(&self) -> Result<f64> {
        Ok(self.jd_utc()? + self.ut1_minus_utc_seconds()? / 86_400.0)
    }
}

fn ut1_history() -> Result<Ut1History> {
    ensure!(
        UT1_C04.len() >= UT1_HEADER_BYTES,
        "invalid SIDERA UT1 asset header"
    );
    ensure!(&UT1_C04[0..4] == b"U1C4", "invalid SIDERA UT1 asset");
    let start_year = u16::from_le_bytes([UT1_C04[4], UT1_C04[5]]) as i32;
    let monthly_count = u16::from_le_bytes([UT1_C04[6], UT1_C04[7]]) as usize;
    let history_end_mjd = i32::from_le_bytes(
        UT1_C04[8..12]
            .try_into()
            .expect("fixed IERS history-end width"),
    );
    let predicted_dut1_ticks = i32::from_le_bytes(
        UT1_C04[12..16]
            .try_into()
            .expect("fixed DUT1 prediction width"),
    );
    ensure!(
        start_year == 2000
            && monthly_count > 0
            && UT1_C04.len() == UT1_HEADER_BYTES + (monthly_count + 1) * 4,
        "invalid SIDERA UT1 history dimensions"
    );
    let final_month_index = monthly_count - 1;
    let final_month_start = julian_day(
        start_year + final_month_index as i32 / 12,
        (final_month_index % 12 + 1) as u32,
        1,
    );
    ensure!(
        history_end_mjd as f64 + MJD_OFFSET > final_month_start,
        "invalid SIDERA UT1 history endpoint"
    );
    Ok(Ut1History {
        start_year,
        monthly_count,
        history_end_jd: history_end_mjd as f64 + MJD_OFFSET,
        predicted_dut1: predicted_dut1_ticks as f64 / UT1_TICKS_PER_SECOND,
    })
}

fn ut1_delta_t_knot(index: usize) -> f64 {
    let offset = UT1_HEADER_BYTES + index * 4;
    i32::from_le_bytes(
        UT1_C04[offset..offset + 4]
            .try_into()
            .expect("validated SIDERA UT1 knot width"),
    ) as f64
        / UT1_TICKS_PER_SECOND
}

fn historical_delta_t(utc: UtcDateTime, history: Ut1History, jd_utc: f64) -> Result<f64> {
    let index = ((utc.year - history.start_year) * 12 + utc.month as i32 - 1) as usize;
    ensure!(
        index < history.monthly_count,
        "UTC date precedes SIDERA IERS history"
    );
    let begin = julian_day(utc.year, utc.month, 1);
    let (end, next) = if index + 1 < history.monthly_count {
        let end = if utc.month == 12 {
            julian_day(utc.year + 1, 1, 1)
        } else {
            julian_day(utc.year, utc.month + 1, 1)
        };
        (end, ut1_delta_t_knot(index + 1))
    } else {
        (
            history.history_end_jd,
            ut1_delta_t_knot(history.monthly_count),
        )
    };
    let current = ut1_delta_t_knot(index);
    let fraction = (jd_utc - begin) / (end - begin);
    Ok(current + fraction * (next - current))
}

pub fn julian_day(year: i32, month: u32, day: u32) -> f64 {
    let a = (14 - month as i32) / 12;
    let y = year + 4800 - a;
    let m = month as i32 + 12 * a - 3;
    (day as i32 + (153 * m + 2) / 5 + 365 * y + y / 4 - y / 100 + y / 400 - 32045) as f64 - 0.5
}

fn days_in_month(year: i32, month: u32) -> u32 {
    match month {
        4 | 6 | 9 | 11 => 30,
        2 if year % 4 == 0 && (year % 100 != 0 || year % 400 == 0) => 29,
        2 => 28,
        _ => 31,
    }
}

fn tai_minus_utc(utc: UtcDateTime) -> f64 {
    // IERS leap-second history. No published future event is invented.
    const LEAPS: &[(i32, u32, u32)] = &[
        (2006, 1, 1),
        (2009, 1, 1),
        (2012, 7, 1),
        (2015, 7, 1),
        (2017, 1, 1),
    ];
    32.0 + LEAPS
        .iter()
        .filter(|&&(y, m, d)| (utc.year, utc.month, utc.day) >= (y, m, d))
        .count() as f64
}

pub fn gmst_iau2006(jd_ut1: f64, jd_tt: f64) -> f64 {
    // IAU 2006 ERA plus P03 precession polynomial; SOFA/ERFA gmst06.
    let t = (jd_tt - JD_J2000) / 36_525.0;
    let era = std::f64::consts::TAU
        * (0.779_057_273_264_0 + 1.002_737_811_911_354_6 * (jd_ut1 - JD_J2000));
    let correction_arcsec = 0.014506
        + t * (4612.156534
            + t * (1.3915817 + t * (-0.00000044 + t * (-0.000029956 - 0.0000000368 * t))));
    (era + correction_arcsec * ARCSEC_TO_RAD).rem_euclid(std::f64::consts::TAU)
}

pub fn gmst_utc(utc: UtcDateTime) -> Result<f64> {
    Ok(gmst_iau2006(utc.jd_ut1()?, utc.jd_tt()?))
}

pub fn gast_utc(utc: UtcDateTime, nutation_longitude: f64, true_obliquity: f64) -> Result<f64> {
    if !nutation_longitude.is_finite() || !true_obliquity.is_finite() {
        bail!("non-finite nutation input")
    }
    Ok((gmst_utc(utc)? + nutation_longitude * true_obliquity.cos())
        .rem_euclid(std::f64::consts::TAU))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn j2000_and_window() {
        let epoch = UtcDateTime::parse("2000-01-01T12:00:00Z").unwrap();
        assert_eq!(epoch.jd_utc().unwrap(), JD_J2000);
        assert!(UtcDateTime::parse("1999-12-31T23:59:59Z").is_err());
        assert!(UtcDateTime::parse("2051-01-01T00:00:00Z").is_err());
        assert!(UtcDateTime::parse("2024-02-30T00:00:00Z").is_err());
    }

    #[test]
    fn iers_delta_t_and_dut1_are_consistent() {
        let epoch = UtcDateTime::parse("2000-01-01T00:00:00Z").unwrap();
        assert!((epoch.delta_t_seconds().unwrap() - 63.828_527_6).abs() < 0.000_002);
        assert!((epoch.ut1_minus_utc_seconds().unwrap() - 0.355_472_4).abs() < 0.000_002);

        let before_leap = UtcDateTime::parse("2012-04-01T00:00:00Z").unwrap();
        assert!((before_leap.ut1_minus_utc_seconds().unwrap() + 0.508_514_6).abs() < 0.000_002);
        let after_leap = UtcDateTime::parse("2012-07-01T00:00:00Z").unwrap();
        assert!((after_leap.ut1_minus_utc_seconds().unwrap() - 0.413_254_1).abs() < 0.000_002);
    }

    #[test]
    fn post_history_dut1_scenario_is_constant() {
        let final_observation = UtcDateTime::parse("2026-08-25T00:00:00Z").unwrap();
        let oracle_2038 = UtcDateTime::parse("2038-03-20T10:00:00Z").unwrap();
        let oracle_2050 = UtcDateTime::parse("2050-12-01T00:00:00Z").unwrap();
        for utc in [final_observation, oracle_2038, oracle_2050] {
            assert!((utc.ut1_minus_utc_seconds().unwrap() - 0.007_054_2).abs() < 0.000_002);
        }
    }

    #[test]
    fn gmst_matches_erfa_iau_2006_reference_across_window() {
        // Independent ERFA gmst06 outputs, radians, at five representative
        // UT1/TT pairs spanning the supported interval.
        let cases = [
            (
                2_451_544.5,
                2_451_544.500_742_870_4,
                1.744_767_234_131_470_4,
            ),
            (
                2_456_018.5,
                2_456_018.500_766_018_4,
                3.311_834_022_343_855_4,
            ),
            (
                2_461_309.416_666_666_5,
                2_461_309.417_467_407,
                5.842_179_008_428_651,
            ),
            (
                2_465_502.916_666_666_5,
                2_465_502.917_467_407,
                5.725_455_760_970_902,
            ),
            (2_470_171.5, 2_470_171.500_800_741, 1.738_720_598_061_619_6),
        ];
        for (ut1, tt, reference) in cases {
            let seconds =
                (gmst_iau2006(ut1, tt) - reference).abs() * 86_400.0 / std::f64::consts::TAU;
            assert!(seconds < 0.1, "GMST error {seconds} seconds at UT1 {ut1}");
        }
    }
}
