// src/shaders/includes/dd.wgsl
// Generated by scripts/generate_dd.py from scripts/dd.wgsl.in.
// Knuth two_sum (6 flops, exact under RN); Dekker/Veltkamp split product.
// Requires determinism.wgsl before this include for det_barrier.
// Joldes, Muller, Popescu (2017) bounds: add <= 3u^2, mul <= 7u^2,
// div <= 15u^2. DUPLA applies the same 15u^2 gate to corrected sqrt.

const DD_ADD_BOUND_U2: f32 = 3.0;
const DD_MUL_BOUND_U2: f32 = 7.0;
const DD_DIV_BOUND_U2: f32 = 15.0;
const DD_SQRT_BOUND_U2: f32 = 15.0;

struct DD { hi: f32, lo: f32 }
struct DDVec3 { x: DD, y: DD, z: DD }

// Knuth two_sum: exact six-flop error-free transform under round-to-nearest.
fn two_sum(a: f32, b: f32) -> DD {
    let hi = a + b;
    let b_virtual = hi - a;
    let a_virtual = hi - b_virtual;
    let b_roundoff = b - b_virtual;
    let a_roundoff = a - a_virtual;
    let lo = a_roundoff + b_roundoff;
    return DD(hi, lo);
}

// Dekker quick_two_sum: exact when abs(a) >= abs(b).
fn quick_two_sum(a: f32, b: f32) -> DD {
    let hi = a + b;
    let lo = b - (hi - a);
    return DD(hi, lo);
}

fn split_scaled(a: f32) -> DD {
    let magnitude = abs(a);
    var scaled = a;
    var undo = 1.0;
    if (magnitude > 1.2676506e30) {
        scaled = det_barrier(a * 3.7252903e-9);
        undo = 268435456.0;
    } else if (magnitude != 0.0 && magnitude < 7.888609e-31) {
        scaled = det_barrier(a * 268435456.0);
        undo = 3.7252903e-9;
    }
    let c = det_barrier(4097.0 * scaled);
    let hi = c - (c - scaled);
    let lo = scaled - hi;
    return DD(det_barrier(hi * undo), det_barrier(lo * undo));
}

// Dekker/Veltkamp scaled split: exact product residual absent overflow.
fn two_prod_split(a: f32, b: f32) -> DD {
    let hi = det_barrier(a * b);
    let sa = split_scaled(a);
    let sb = split_scaled(b);
    let e0 = det_barrier(sa.hi * sb.hi) - hi;
    let e1 = e0 + det_barrier(sa.hi * sb.lo);
    let e2 = e1 + det_barrier(sa.lo * sb.hi);
    let lo = e2 + det_barrier(sa.lo * sb.lo);
    return DD(hi, lo);
}

// IEEE fma residual: exact product residual when the backend canary accepts it.
fn two_prod_fma(a: f32, b: f32) -> DD {
    let hi = det_barrier(a * b);
    let lo = fma(a, b, -hi);
    return DD(hi, lo);
}

fn two_prod(a: f32, b: f32) -> DD {
    return __DD_TWO_PROD_CALL__(a, b);
}

fn dd_renorm(value: DD) -> DD {
    return quick_two_sum(value.hi, value.lo);
}

// Joldes-Muller-Popescu accurate double-word add: relative error <= 3u^2.
fn dd_add(a: DD, b: DD) -> DD {
    let s = two_sum(a.hi, b.hi);
    let t = two_sum(a.lo, b.lo);
    let merged = quick_two_sum(s.hi, s.lo + t.hi);
    return quick_two_sum(merged.hi, merged.lo + t.lo);
}

fn dd_sub(a: DD, b: DD) -> DD {
    return dd_add(a, DD(-b.hi, -b.lo));
}

// Joldes-Muller-Popescu double-word multiply: relative error <= 7u^2.
fn dd_mul(a: DD, b: DD) -> DD {
    let p = two_prod(a.hi, b.hi);
    let cross0 = det_barrier(a.hi * b.lo);
    let cross1 = det_barrier(a.lo * b.hi);
    let correction = (p.lo + cross0) + cross1;
    return quick_two_sum(p.hi, correction);
}

fn dd_reciprocal_refine(x: f32) -> f32 {
    let ax = abs(x);
    var y = bitcast<f32>(0x7ef311c3u - bitcast<u32>(ax));
    y = det_barrier(y * (2.0 - det_barrier(ax * y)));
    y = det_barrier(y * (2.0 - det_barrier(ax * y)));
    y = det_barrier(y * (2.0 - det_barrier(ax * y)));
    y = det_barrier(y * (2.0 - det_barrier(ax * y)));
    if (x < 0.0) { return -y; }
    return y;
}

// Joldes-Muller-Popescu corrected divide: relative error <= 15u^2.
fn dd_div(a: DD, b: DD) -> DD {
    let reciprocal = dd_reciprocal_refine(b.hi);
    let q_hi = det_barrier(a.hi * reciprocal);
    let q = DD(q_hi, 0.0);
    let remainder = dd_sub(a, dd_mul(b, q));
    let q_lo = det_barrier((remainder.hi + remainder.lo) * reciprocal);
    return dd_add(q, DD(q_lo, 0.0));
}

fn dd_inverse_sqrt_seed(x: f32) -> f32 {
    return inverseSqrt(x);
}

fn inverse_sqrt_residual(x: f32, y: f32) -> f32 {
    return abs(1.0 - det_barrier(x * det_barrier(y * y)));
}

fn dd_inverse_sqrt_refine(x: f32, seed: f32) -> f32 {
    let half_x = det_barrier(0.5 * x);
    var y = seed;
    y = det_barrier(y * (1.5 - det_barrier(half_x * det_barrier(y * y))));
    y = det_barrier(y * (1.5 - det_barrier(half_x * det_barrier(y * y))));
    y = det_barrier(y * (1.5 - det_barrier(half_x * det_barrier(y * y))));
    var best = y;
    var best_bits = bitcast<u32>(y);
    var best_error = inverse_sqrt_residual(x, y);
    let below_bits = best_bits - 1u;
    let below = bitcast<f32>(below_bits);
    let below_error = inverse_sqrt_residual(x, below);
    if (below_error < best_error || (below_error == best_error && below_bits < best_bits)) {
        best = below;
        best_bits = below_bits;
        best_error = below_error;
    }
    let above_bits = bitcast<u32>(y) + 1u;
    let above = bitcast<f32>(above_bits);
    let above_error = inverse_sqrt_residual(x, above);
    if (above_error < best_error || (above_error == best_error && above_bits < best_bits)) {
        best = above;
    }
    return best;
}

// Newton inverse-sqrt plus one correction: DUPLA relative-error gate <= 15u^2.
fn dd_sqrt(a: DD) -> DD {
    if (a.hi == 0.0) { return DD(0.0, 0.0); }
    let inverse = dd_inverse_sqrt_refine(a.hi, dd_inverse_sqrt_seed(a.hi));
    let root_hi = det_barrier(a.hi * inverse);
    let root = DD(root_hi, 0.0);
    let remainder = dd_sub(a, dd_mul(root, root));
    let root_lo = det_barrier(det_barrier(0.5 * remainder.hi) * inverse);
    return dd_add(root, DD(root_lo, 0.0));
}

fn dd_dot3(a: DDVec3, b: DDVec3) -> DD {
    return dd_add(dd_add(dd_mul(a.x, b.x), dd_mul(a.y, b.y)), dd_mul(a.z, b.z));
}

fn dd_length3(value: DDVec3) -> DD {
    return dd_sqrt(dd_dot3(value, value));
}

fn dd_sub_vec3(a: DDVec3, b: DDVec3) -> DDVec3 {
    return DDVec3(dd_sub(a.x, b.x), dd_sub(a.y, b.y), dd_sub(a.z, b.z));
}
