// src/shaders/includes/dd.wgsl
// Generated by scripts/generate_dd.py from scripts/dd.wgsl.in.
// Knuth two_sum (6 flops, exact under RN); Dekker/Veltkamp split product.
// Requires determinism.wgsl before this include for dd_barrier.
// Joldes, Muller, Popescu (2017) bounds: add <= 3u^2, mul <= 7u^2,
// div <= 15u^2. DUPLA applies the same 15u^2 gate to corrected sqrt.

const DD_ADD_BOUND_U2: f32 = 3.0;
const DD_MUL_BOUND_U2: f32 = 7.0;
const DD_DIV_BOUND_U2: f32 = 15.0;
const DD_SQRT_BOUND_U2: f32 = 15.0;

struct DD { hi: f32, lo: f32 }
struct DDVec3 { x: DD, y: DD, z: DD }

fn dd_barrier(value: f32) -> f32 {
    __DD_BARRIER_BODY__
}

// Knuth two_sum: exact six-flop error-free transform under round-to-nearest.
fn two_sum_subnormal(a: f32, b: f32, a_bits: u32, b_bits: u32, a_sub: bool, b_sub: bool) -> DD {
    if (a_sub && b_sub) {
        var a_signed = i32(a_bits & 0x007fffffu);
        if ((a_bits & 0x80000000u) != 0u) { a_signed = -a_signed; }
        var b_signed = i32(b_bits & 0x007fffffu);
        if ((b_bits & 0x80000000u) != 0u) { b_signed = -b_signed; }
        let total = a_signed + b_signed;
        if (total == 0) { return DD(0.0, 0.0); }
        var sign = 0u;
        var magnitude = total;
        if (magnitude < 0) { sign = 0x80000000u; magnitude = -magnitude; }
        return DD(bitcast<f32>(sign | u32(magnitude)), 0.0);
    }
    if (a_sub && (b_bits & 0x7fffffffu) == 0u) { return DD(a, 0.0); }
    if (b_sub && (a_bits & 0x7fffffffu) == 0u) { return DD(b, 0.0); }
    if (a_sub) { return DD(b, a); }
    return DD(a, b);
}

fn two_sum(a: f32, b: f32) -> DD {
    let a_bits = bitcast<u32>(a);
    let b_bits = bitcast<u32>(b);
    let a_sub = (a_bits & 0x007fffffu) != 0u && (a_bits & 0x7f800000u) == 0u;
    let b_sub = (b_bits & 0x007fffffu) != 0u && (b_bits & 0x7f800000u) == 0u;
    if (a_sub || b_sub) {
        return two_sum_subnormal(a, b, a_bits, b_bits, a_sub, b_sub);
    }
    let hi = dd_barrier(a + b);
    let b_virtual = dd_barrier(hi - a);
    let a_virtual = dd_barrier(hi - b_virtual);
    let b_roundoff = dd_barrier(b - b_virtual);
    let a_roundoff = dd_barrier(a - a_virtual);
    let lo = dd_barrier(a_roundoff + b_roundoff);
    return DD(hi, lo);
}

// Dekker quick_two_sum: exact when abs(a) >= abs(b).
fn quick_two_sum(a: f32, b: f32) -> DD {
    let hi = dd_barrier(a + b);
    let lo = dd_barrier(b - dd_barrier(hi - a));
    return DD(hi, lo);
}

struct ScaledOperand { value: f32, shifts: u32 }

fn normalize_subnormal(value: f32) -> ScaledOperand {
    let bits = bitcast<u32>(value);
    let mantissa = bits & 0x007fffffu;
    if (mantissa == 0u || (bits & 0x7f800000u) != 0u) {
        return ScaledOperand(value, 0u);
    }
    let leading = 31u - countLeadingZeros(mantissa);
    let shift = 23u - leading;
    let normalized = (bits & 0x80000000u) | ((leading + 2u) << 23u) | ((mantissa << shift) & 0x007fffffu);
    return ScaledOperand(dd_barrier(bitcast<f32>(normalized)), 1u);
}

fn split_scaled(a: f32) -> DD {
    let magnitude = abs(a);
    var scaled = a;
    var undo = 1.0;
    if (magnitude > 1.2676506e30) {
        scaled = dd_barrier(a * 3.7252903e-9);
        undo = 268435456.0;
    } else if (magnitude != 0.0 && magnitude < 7.888609e-31) {
        scaled = dd_barrier(a * 268435456.0);
        undo = 3.7252903e-9;
    }
    let c = dd_barrier(4097.0 * scaled);
    let hi = c - (c - scaled);
    let lo = scaled - hi;
    return DD(dd_barrier(hi * undo), dd_barrier(lo * undo));
}

// Dekker/Veltkamp scaled split: exact product residual absent overflow.
fn two_prod_split_raw(a: f32, b: f32) -> DD {
    let hi = dd_barrier(a * b);
    let sa = split_scaled(a);
    let sb = split_scaled(b);
    let e0 = dd_barrier(dd_barrier(sa.hi * sb.hi) - hi);
    let e1 = dd_barrier(e0 + dd_barrier(sa.hi * sb.lo));
    let e2 = dd_barrier(e1 + dd_barrier(sa.lo * sb.hi));
    let lo = dd_barrier(e2 + dd_barrier(sa.lo * sb.lo));
    return DD(hi, lo);
}

fn two_prod_split(a: f32, b: f32) -> DD {
    let sa = normalize_subnormal(a);
    let sb = normalize_subnormal(b);
    var aa = sa.value;
    var bb = sb.value;
    if (sa.shifts > 0u) { bb = dd_barrier(bb * 5.9604645e-8); }
    if (sb.shifts > 0u) { aa = dd_barrier(aa * 5.9604645e-8); }
    let result = two_prod_split_raw(aa, bb);
    if (result.hi == 0.0 && result.lo == 0.0) { return DD(0.0, 0.0); }
    return result;
}

// IEEE fma residual: exact product residual when the backend canary accepts it.
fn two_prod_fma_raw(a: f32, b: f32) -> DD {
    let hi = dd_barrier(a * b);
    let lo = fma(a, b, -hi);
    return DD(hi, lo);
}

fn two_prod_fma(a: f32, b: f32) -> DD {
    let sa = normalize_subnormal(a);
    let sb = normalize_subnormal(b);
    var aa = sa.value;
    var bb = sb.value;
    if (sa.shifts > 0u) { bb = dd_barrier(bb * 5.9604645e-8); }
    if (sb.shifts > 0u) { aa = dd_barrier(aa * 5.9604645e-8); }
    let result = two_prod_fma_raw(aa, bb);
    if (result.hi == 0.0 && result.lo == 0.0) { return DD(0.0, 0.0); }
    return result;
}

fn two_prod(a: f32, b: f32) -> DD {
    return __DD_TWO_PROD_CALL__(a, b);
}

fn dd_renorm(value: DD) -> DD {
    return quick_two_sum(value.hi, value.lo);
}

fn dd_canonicalize_tie(value: DD) -> DD {
    let bits = bitcast<u32>(value.hi);
    let biased = (bits >> 23u) & 0xffu;
    if (biased <= 24u || (bits & 1u) == 0u) { return value; }
    let half_ulp = bitcast<f32>((biased - 24u) << 23u);
    let lo_bits = bitcast<u32>(abs(value.lo));
    let half_bits = bitcast<u32>(half_ulp);
    if (lo_bits > half_bits || half_bits - lo_bits > 1u) { return value; }
    let increment = (value.lo > 0.0) != (value.hi < 0.0);
    var adjacent_bits = bits - 1u;
    if (increment) { adjacent_bits = bits + 1u; }
    return DD(bitcast<f32>(adjacent_bits), -value.lo);
}

// Joldes-Muller-Popescu accurate double-word add: relative error <= 3u^2.
fn dd_add(a: DD, b: DD) -> DD {
    let s = two_sum(a.hi, b.hi);
    let t = two_sum(a.lo, b.lo);
    let merged = quick_two_sum(s.hi, dd_barrier(s.lo + t.hi));
    return quick_two_sum(merged.hi, dd_barrier(merged.lo + t.lo));
}

fn dd_sub(a: DD, b: DD) -> DD {
    return dd_add(a, DD(-b.hi, -b.lo));
}

// Joldes-Muller-Popescu double-word multiply: relative error <= 7u^2.
fn dd_mul(a: DD, b: DD) -> DD {
    let p = two_prod(a.hi, b.hi);
    let cross0 = dd_barrier(a.hi * b.lo);
    let cross1 = dd_barrier(a.lo * b.hi);
    let correction = dd_barrier(dd_barrier(p.lo + cross0) + cross1);
    return quick_two_sum(p.hi, correction);
}

fn dd_mul_split_fixed(a: DD, b: DD) -> DD {
    let p = two_prod_split(a.hi, b.hi);
    let cross0 = dd_barrier(a.hi * b.lo);
    let cross1 = dd_barrier(a.lo * b.hi);
    let correction = dd_barrier(dd_barrier(p.lo + cross0) + cross1);
    return quick_two_sum(p.hi, correction);
}

// Newton-Raphson reciprocal from multiplication/addition only (JMP 2017 division setup).
fn dd_reciprocal_refine(x: f32) -> f32 {
    let ax = abs(x);
    var y = bitcast<f32>(0x7ef311c3u - bitcast<u32>(ax));
    y = dd_barrier(y * (2.0 - dd_barrier(ax * y)));
    y = dd_barrier(y * (2.0 - dd_barrier(ax * y)));
    y = dd_barrier(y * (2.0 - dd_barrier(ax * y)));
    y = dd_barrier(y * (2.0 - dd_barrier(ax * y)));
    if (x < 0.0) { return -y; }
    return y;
}

// Joldes-Muller-Popescu corrected divide: relative error <= 15u^2.
fn dd_div(a: DD, b: DD) -> DD {
    let reciprocal = dd_reciprocal_refine(b.hi);
    let q_hi = dd_barrier(a.hi * reciprocal);
    let q = DD(q_hi, 0.0);
    let remainder = dd_sub(a, dd_mul(b, q));
    let q_lo = dd_barrier((remainder.hi + remainder.lo) * reciprocal);
    let first = dd_add(q, DD(q_lo, 0.0));
    let final_remainder = dd_sub(a, dd_mul(b, first));
    let final_lo = dd_barrier((final_remainder.hi + final_remainder.lo) * reciprocal);
    return dd_add(first, DD(final_lo, 0.0));
}

// Hardware inverse-sqrt is a seed only; no error-free step depends on its accuracy.
fn dd_inverse_sqrt_seed(x: f32) -> f32 {
    return inverseSqrt(x);
}

fn inverse_sqrt_residual(x: f32, y: f32) -> DD {
    let yy = dd_mul_split_fixed(DD(y, 0.0), DD(y, 0.0));
    let xyy = dd_mul_split_fixed(DD(x, 0.0), yy);
    return dd_sub(DD(1.0, 0.0), xyy);
}

fn inverse_sqrt_residual_better(candidate: DD, best: DD) -> bool {
    return abs(candidate.hi) < abs(best.hi)
        || (abs(candidate.hi) == abs(best.hi) && abs(candidate.lo) < abs(best.lo));
}

fn inverse_sqrt_residual_equal(candidate: DD, best: DD) -> bool {
    return candidate.hi == best.hi && candidate.lo == best.lo;
}

// Newton inverse-square-root refinement using multiplication/addition only.
fn dd_inverse_sqrt_refine(x: f32, seed: f32) -> f32 {
    let half_x = dd_barrier(0.5 * x);
    var y = seed;
    y = dd_barrier(y * (1.5 - dd_barrier(half_x * dd_barrier(y * y))));
    y = dd_barrier(y * (1.5 - dd_barrier(half_x * dd_barrier(y * y))));
    y = dd_barrier(y * (1.5 - dd_barrier(half_x * dd_barrier(y * y))));
    y = dd_barrier(y * (1.5 - dd_barrier(half_x * dd_barrier(y * y))));
    var best = y;
    var best_bits = bitcast<u32>(y);
    var best_error = inverse_sqrt_residual(x, y);
    let below_bits = best_bits - 1u;
    let below = bitcast<f32>(below_bits);
    let below_error = inverse_sqrt_residual(x, below);
    if (inverse_sqrt_residual_better(below_error, best_error)
        || (inverse_sqrt_residual_equal(below_error, best_error) && below_bits < best_bits)) {
        best = below;
        best_bits = below_bits;
        best_error = below_error;
    }
    let above_bits = bitcast<u32>(y) + 1u;
    let above = bitcast<f32>(above_bits);
    let above_error = inverse_sqrt_residual(x, above);
    if (inverse_sqrt_residual_better(above_error, best_error)
        || (inverse_sqrt_residual_equal(above_error, best_error) && above_bits < best_bits)) {
        best = above;
    }
    return best;
}

// Newton inverse-sqrt plus two residual corrections: DUPLA relative-error gate <= 15u^2.
fn dd_sqrt(a: DD) -> DD {
    if (a.hi == 0.0) { return DD(0.0, 0.0); }
    let inverse = dd_inverse_sqrt_refine(a.hi, dd_inverse_sqrt_seed(a.hi));
    let root_hi = dd_barrier(a.hi * inverse);
    let root = DD(root_hi, 0.0);
    let remainder = dd_sub(a, dd_mul(root, root));
    let inverse_two_root = dd_reciprocal_refine(dd_barrier(2.0 * root_hi));
    let root_lo = dd_barrier(dd_barrier(remainder.hi + remainder.lo) * inverse_two_root);
    let first = dd_add(root, DD(root_lo, 0.0));
    let canonical_root = DD(first.hi, 0.0);
    let canonical_remainder = dd_sub(a, dd_mul(canonical_root, canonical_root));
    let canonical_inverse = dd_reciprocal_refine(dd_barrier(2.0 * first.hi));
    let canonical_lo = dd_barrier(
        dd_barrier(canonical_remainder.hi + canonical_remainder.lo) * canonical_inverse);
    return dd_canonicalize_tie(dd_add(canonical_root, DD(canonical_lo, 0.0)));
}

fn dd_dot3(a: DDVec3, b: DDVec3) -> DD {
    return dd_add(dd_add(dd_mul(a.x, b.x), dd_mul(a.y, b.y)), dd_mul(a.z, b.z));
}

fn dd_length3(value: DDVec3) -> DD {
    return dd_sqrt(dd_dot3(value, value));
}

fn dd_sub_vec3(a: DDVec3, b: DDVec3) -> DDVec3 {
    return DDVec3(dd_sub(a.x, b.x), dd_sub(a.y, b.y), dd_sub(a.z, b.z));
}
