//! BOP-P2-02: Terrain geometry provider — grid | clipmap.
//!
//! `TerrainRenderer` historically expanded a procedural grid inside `vs_main`
//! from the vertex index alone. This module makes the geometry source an
//! explicit choice per frame: the procedural grid (fullscreen triangle, mesh
//! grid) or the indexed clipmap ring/skirt mesh generated by
//! `crate::terrain::clipmap`, drawn through `vs_clipmap_main` in the shared
//! terrain PBR shader.
//!
//! Secondary terrain passes (water reflection, CSM shadow cascades) still use
//! the procedural-grid proxy via `terrain_vertex_count`; the beauty, AOV, and
//! offline accumulation passes all consume this provider.

use super::*;
use crate::core::resource_tracker::{tracked_create_buffer_init, TrackedBuffer};
use crate::terrain::clipmap::ClipmapConfig;

/// Cache key for the generated clipmap mesh. Regeneration only happens when
/// the clipmap configuration, terrain span, or streaming center changes —
/// not every frame.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(in crate::terrain::renderer) struct ClipmapGeometryKey {
    ring_count: u32,
    ring_resolution: u32,
    center_resolution: u32,
    skirt_depth_bits: u32,
    morph_range_bits: u32,
    terrain_span_bits: u32,
    center_bits: (u32, u32),
}

impl ClipmapGeometryKey {
    pub(in crate::terrain::renderer) fn new(
        config: &ClipmapConfig,
        terrain_span: f32,
        center: glam::Vec2,
    ) -> Self {
        Self {
            ring_count: config.ring_count,
            ring_resolution: config.ring_resolution,
            center_resolution: config.center_resolution,
            skirt_depth_bits: config.skirt_depth.to_bits(),
            morph_range_bits: config.morph_range.to_bits(),
            terrain_span_bits: terrain_span.to_bits(),
            center_bits: (center.x.to_bits(), center.y.to_bits()),
        }
    }
}

/// Geometry source for the terrain main/AOV/offline passes.
pub(in crate::terrain::renderer) enum TerrainGeometryProvider {
    /// Procedural geometry expanded in `vs_main` from the vertex index.
    Grid { vertex_count: u32 },
    /// Indexed clipmap ring/skirt mesh drawn through `vs_clipmap_main`.
    Clipmap {
        vertex_buffer: TrackedBuffer,
        index_buffer: TrackedBuffer,
        index_count: u32,
        cache_key: ClipmapGeometryKey,
    },
}

impl TerrainGeometryProvider {
    pub(in crate::terrain::renderer) fn is_clipmap(&self) -> bool {
        matches!(self, Self::Clipmap { .. })
    }

    /// Issue the draw for this geometry. The caller must have selected the
    /// matching pipeline (`vs_main` for `Grid`, `vs_clipmap_main` for
    /// `Clipmap`) before calling.
    pub(in crate::terrain::renderer) fn draw<'p>(&'p self, pass: &mut wgpu::RenderPass<'p>) {
        match self {
            Self::Grid { vertex_count } => pass.draw(0..*vertex_count, 0..1),
            Self::Clipmap {
                vertex_buffer,
                index_buffer,
                index_count,
                ..
            } => {
                pass.set_vertex_buffer(0, vertex_buffer.slice(..));
                pass.set_index_buffer(index_buffer.slice(..), wgpu::IndexFormat::Uint32);
                pass.draw_indexed(0..*index_count, 0, 0..1);
            }
        }
    }
}

impl TerrainScene {
    /// Build (or reuse) the geometry provider for this frame.
    ///
    /// `clipmap` camera modes always produce the indexed ring/skirt mesh —
    /// there is no backend-dependent fallback. When height streaming is
    /// active the clipmap recenters on the streaming center so rings follow
    /// the camera.
    pub(in crate::terrain::renderer) fn prepare_geometry(
        &mut self,
        params: &crate::terrain::render_params::TerrainRenderParams,
    ) -> Result<()> {
        let Some(config) = clipmap_camera_config(&params.camera_mode) else {
            self.geometry_provider = Some(TerrainGeometryProvider::Grid {
                vertex_count: self.terrain_vertex_count(params),
            });
            return Ok(());
        };

        let center = self.height_streaming_center();
        let terrain_span = params.terrain_span.max(1.0);
        let cache_key = ClipmapGeometryKey::new(&config, terrain_span, center);
        if let Some(TerrainGeometryProvider::Clipmap {
            cache_key: existing,
            ..
        }) = self.geometry_provider.as_ref()
        {
            if *existing == cache_key {
                return Ok(());
            }
        }

        let mesh = crate::terrain::clipmap::level::clipmap_generate(&config, center, terrain_span);
        let vertex_buffer = tracked_create_buffer_init(
            self.device.as_ref(),
            &wgpu::util::BufferInitDescriptor {
                label: Some("terrain.clipmap.vertex_buffer"),
                contents: bytemuck::cast_slice(&mesh.vertices),
                usage: wgpu::BufferUsages::VERTEX,
            },
        )?;
        let index_buffer = tracked_create_buffer_init(
            self.device.as_ref(),
            &wgpu::util::BufferInitDescriptor {
                label: Some("terrain.clipmap.index_buffer"),
                contents: bytemuck::cast_slice(&mesh.indices),
                usage: wgpu::BufferUsages::INDEX,
            },
        )?;
        self.geometry_provider = Some(TerrainGeometryProvider::Clipmap {
            vertex_buffer,
            index_buffer,
            index_count: mesh.index_count(),
            cache_key,
        });
        Ok(())
    }

    pub(in crate::terrain::renderer) fn geometry_provider(
        &self,
    ) -> Result<&TerrainGeometryProvider> {
        self.geometry_provider
            .as_ref()
            .ok_or_else(|| anyhow!("terrain geometry provider not prepared for this frame"))
    }
}
