use crate::cli::args::GiVizMode;

use super::{
    ViewerDenoiseConfig, ViewerDofConfig, ViewerHeightAoConfig, ViewerLensEffectsConfig,
    ViewerMaterialLayerConfig, ViewerMotionBlurConfig, ViewerSkyConfig, ViewerSunVisConfig,
    ViewerTonemapConfig, ViewerVectorOverlayConfig, ViewerVolumetricsConfig,
};

/// Viewer command enum for input parsing.
#[rustfmt::skip]
#[derive(Debug, Clone)]
pub enum ViewerCmd {
    GiToggle(&'static str, bool), SetGiSeed(u32), Snapshot(Option<String>), DumpGbuffer, Quit,
    SaveBundle { path: String, name: Option<String> },
    LoadBundle { path: String },
    LoadObj(String), LoadGltf(String), SetViz(String), SetGiViz(GiVizMode), QueryGiViz,
    LoadSsrPreset, LoadIbl(String), IblToggle(bool), IblIntensity(f32), IblRotate(f32),
    IblCache(Option<String>), IblRes(u32),
    #[allow(dead_code)] SetSsaoRadius(f32),
    #[allow(dead_code)] SetSsaoIntensity(f32),
    #[allow(dead_code)] SetSsaoBias(f32),
    #[allow(dead_code)] SetSsgiSteps(u32),
    #[allow(dead_code)] SetSsgiRadius(f32),
    SetSsrMaxSteps(u32), SetSsrThickness(f32),
    #[allow(dead_code)] SetSsgiHalf(bool),
    #[allow(dead_code)] SetSsgiTemporalAlpha(f32),
    #[allow(dead_code)] SetSsgiTemporalEnabled(bool),
    #[allow(dead_code)] SetAoTemporalAlpha(f32),
    #[allow(dead_code)] SetSsaoSamples(u32),
    #[allow(dead_code)] SetSsaoDirections(u32),
    #[allow(dead_code)] SetSsaoTemporalAlpha(f32),
    #[allow(dead_code)] SetSsaoTemporalEnabled(bool),
    #[allow(dead_code)] SetSsaoTechnique(u32),
    #[allow(dead_code)] SetVizDepthMax(f32),
    #[allow(dead_code)] SetFov(f32),
    #[allow(dead_code)] SetCamLookAt { eye: [f32; 3], target: [f32; 3], up: [f32; 3] },
    #[allow(dead_code)] SetSize(u32, u32),
    #[allow(dead_code)] SetSsaoComposite(bool),
    #[allow(dead_code)] SetSsaoCompositeMul(f32),
    #[allow(dead_code)] SetAoBlur(bool),
    QuerySsaoRadius, QuerySsaoIntensity, QuerySsaoBias, QuerySsaoSamples, QuerySsaoDirections,
    QuerySsaoTemporalAlpha, QuerySsaoTemporalEnabled, QuerySsaoBlur, QuerySsaoComposite,
    QuerySsaoMul, QuerySsaoTechnique, QuerySsgiSteps, QuerySsgiRadius, QuerySsgiHalf,
    QuerySsgiTemporalAlpha, QuerySsgiTemporalEnabled, QuerySsgiEdges,
    QuerySsgiUpsampleSigmaDepth, QuerySsgiUpsampleSigmaNormal, QuerySsrEnable, QuerySsrMaxSteps,
    QuerySsrThickness, QueryGiAoWeight, QueryGiSsgiWeight, QueryGiSsrWeight,
    #[allow(dead_code)] SetSsgiEdges(bool),
    #[allow(dead_code)] SetSsgiUpsampleSigmaDepth(f32),
    #[allow(dead_code)] SetSsgiUpsampleSigmaNormal(f32),
    SetGiAoWeight(f32), SetGiSsgiWeight(f32), SetGiSsrWeight(f32), SetLitSun(f32),
    SetLitIbl(f32), SetLitBrdf(u32), SetLitRough(f32), SetLitDebug(u32), SkyToggle(bool),
    SkySetModel(u32), SkySetTurbidity(f32), SkySetGround(f32), SkySetExposure(f32),
    SkySetSunIntensity(f32), FogToggle(bool), FogSetDensity(f32), FogSetG(f32), FogSetSteps(u32),
    FogSetShadow(bool), FogSetTemporal(f32), SetFogMode(u32), FogPreset(u32), FogHalf(bool),
    FogEdges(bool), FogUpsigma(f32), HudToggle(bool), CaptureP51Cornell, CaptureP51Grid,
    CaptureP51Sweep, CaptureP52SsgiCornell, CaptureP52SsgiTemporal, CaptureP53SsrGlossy,
    CaptureP53SsrThickness, CaptureP54GiStack, QueryGiSeed, GiStatus,

    SetSunDirection { azimuth_deg: f32, elevation_deg: f32 },
    SetIbl { path: String, intensity: f32 },
    SetZScale(f32),
    SnapshotWithSize { path: String, width: Option<u32>, height: Option<u32> },
    SetTransform { translation: Option<[f32; 3]>, rotation_quat: Option<[f32; 4]>, scale: Option<[f32; 3]> },
    LoadTerrain(String),
    SetTerrainCamera { phi_deg: f32, theta_deg: f32, radius: f32, fov_deg: f32 },
    SetTerrainSun { azimuth_deg: f32, elevation_deg: f32, intensity: f32 },
    SetTerrain {
        phi: Option<f32>, theta: Option<f32>, radius: Option<f32>, fov: Option<f32>,
        sun_azimuth: Option<f32>, sun_elevation: Option<f32>, sun_intensity: Option<f32>,
        ambient: Option<f32>, zscale: Option<f32>, shadow: Option<f32>,
        background: Option<[f32; 3]>, water_level: Option<f32>, water_color: Option<[f32; 3]>,
    },
    GetTerrainParams,
    SetTerrainPbr {
        enabled: Option<bool>, hdr_path: Option<String>, ibl_intensity: Option<f32>,
        shadow_technique: Option<String>, shadow_map_res: Option<u32>, exposure: Option<f32>,
        msaa: Option<u32>, normal_strength: Option<f32>,
        height_ao: Box<Option<ViewerHeightAoConfig>>, sun_visibility: Box<Option<ViewerSunVisConfig>>,
        materials: Box<Option<ViewerMaterialLayerConfig>>, vector_overlay: Box<Option<ViewerVectorOverlayConfig>>,
        tonemap: Option<ViewerTonemapConfig>, dof: Box<Option<ViewerDofConfig>>,
        motion_blur: Option<ViewerMotionBlurConfig>, lens_effects: Option<ViewerLensEffectsConfig>,
        denoise: Option<ViewerDenoiseConfig>, volumetrics: Box<Option<ViewerVolumetricsConfig>>,
        sky: Option<ViewerSkyConfig>, debug_mode: Option<u32>,
    },

    LoadOverlay { name: String, path: String, extent: Option<[f32; 4]>, opacity: Option<f32>, z_order: Option<i32> },
    RemoveOverlay { id: u32 }, SetOverlayVisible { id: u32, visible: bool },
    SetOverlayOpacity { id: u32, opacity: f32 }, SetGlobalOverlayOpacity { opacity: f32 },
    SetOverlaysEnabled { enabled: bool }, SetOverlaySolid { solid: bool }, ListOverlays,
    AddVectorOverlay {
        name: String, vertices: Vec<[f32; 8]>, indices: Vec<u32>, primitive: String, drape: bool,
        drape_offset: f32, opacity: f32, depth_bias: f32, line_width: f32, point_size: f32, z_order: i32,
    },
    RemoveVectorOverlay { id: u32 }, SetVectorOverlayVisible { id: u32, visible: bool },
    SetVectorOverlayOpacity { id: u32, opacity: f32 }, ListVectorOverlays,
    SetVectorOverlaysEnabled { enabled: bool }, SetGlobalVectorOverlayOpacity { opacity: f32 },

    LoadPointCloud { path: String, point_size: f32, max_points: u64, color_mode: Option<String> },
    ClearPointCloud,
    SetPointCloudParams {
        point_size: Option<f32>,
        visible: Option<bool>,
        color_mode: Option<String>,
        phi: Option<f32>,
        theta: Option<f32>,
        radius: Option<f32>,
    },
    AddLabel {
        text: String, world_pos: [f32; 3], size: Option<f32>, color: Option<[f32; 4]>,
        halo_color: Option<[f32; 4]>, halo_width: Option<f32>, priority: Option<i32>,
        min_zoom: Option<f32>, max_zoom: Option<f32>, offset: Option<[f32; 2]>, rotation: Option<f32>,
        underline: Option<bool>, small_caps: Option<bool>, leader: Option<bool>, horizon_fade_angle: Option<f32>,
    },
    AddLineLabel {
        text: String, polyline: Vec<[f32; 3]>, size: Option<f32>, color: Option<[f32; 4]>,
        halo_color: Option<[f32; 4]>, halo_width: Option<f32>, priority: Option<i32>,
        placement: Option<String>, repeat_distance: Option<f32>, min_zoom: Option<f32>, max_zoom: Option<f32>,
    },
    RemoveLabel { id: u64 }, ClearLabels, SetLabelsEnabled { enabled: bool },
    LoadLabelAtlas { atlas_png_path: String, metrics_json_path: String },
    SetLabelZoom { zoom: f32 }, SetMaxVisibleLabels { max: usize },
    AddCurvedLabel {
        text: String, polyline: Vec<[f32; 3]>, size: Option<f32>, color: Option<[f32; 4]>,
        halo_color: Option<[f32; 4]>, halo_width: Option<f32>, priority: Option<i32>,
        tracking: Option<f32>, center_on_path: bool,
    },
    AddCallout {
        text: String, anchor: [f32; 3], offset: Option<[f32; 2]>, background_color: Option<[f32; 4]>,
        border_color: Option<[f32; 4]>, border_width: Option<f32>, corner_radius: Option<f32>,
        padding: Option<f32>, text_size: Option<f32>, text_color: Option<[f32; 4]>,
    },
    RemoveCallout { id: u64 },
    SetLabelTypography { tracking: Option<f32>, kerning: Option<bool>, line_height: Option<f32>, word_spacing: Option<f32> },
    SetDeclutterAlgorithm { algorithm: String, seed: Option<u64>, max_iterations: Option<usize> },
    PollPickEvents, SetLassoMode { enabled: bool }, GetLassoState, ClearSelection,
    SetOitEnabled { enabled: bool, mode: String }, GetOitMode, SetTaaEnabled { enabled: bool }, GetTaaStatus,
    SetTaaParams { history_weight: Option<f32>, jitter_scale: Option<f32>, enable_jitter: Option<bool> },
}
