# examples/f9_primitives_demo.py
# Samples primitive meshes generated by the geometry module
# Exists to showcase F9 coverage and basic stats for each primitive
# RELEVANT FILES:src/geometry/primitives.rs,python/forge3d/geometry.py,tests/test_f9_primitives.py,tests/test_f15_validate.py

from __future__ import annotations

import argparse

from _import_shim import ensure_repo_import

ensure_repo_import()

import forge3d.geometry as geometry  # noqa: E402

PRIMITIVES = ("plane", "box", "sphere", "cylinder", "cone", "torus")


def describe(kind: str) -> None:
    mesh = geometry.primitive_mesh(kind)
    print(f"{kind}: vertices={mesh.vertex_count} triangles={mesh.triangle_count}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Report stats for unit primitives")
    parser.add_argument(
        "--include",
        nargs="*",
        default=list(PRIMITIVES),
        help="Subset of primitives to generate",
    )
    args = parser.parse_args()

    print("forge3d F9 primitive mesh demo")
    for kind in args.include:
        if kind not in PRIMITIVES:
            print(f"skipping unsupported primitive: {kind}")
            continue
        describe(kind)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
