// Generated by scripts/generate_dd.py from scripts/dd_product.rs.in.
use super::*;

struct ScaledOperand {
    value: f32,
    shifts: u32,
}

fn normalize_subnormal(value: f32) -> ScaledOperand {
    let bits = value.to_bits();
    let mantissa = bits & 0x007f_ffff;
    if mantissa == 0 || bits & 0x7f80_0000 != 0 {
        return ScaledOperand { value, shifts: 0 };
    }
    let leading = 31 - mantissa.leading_zeros();
    let shift = 23 - leading;
    let normalized =
        (bits & 0x8000_0000) | ((leading + 2) << 23) | ((mantissa << shift) & 0x007f_ffff);
    ScaledOperand {
        value: dd_barrier(f32::from_bits(normalized)),
        shifts: 1,
    }
}

fn split_scaled(a: f32) -> DD {
    let magnitude = a.abs();
    let mut scaled = a;
    let mut undo = 1.0;
    if magnitude > 1.267_650_6e30 {
        scaled = dd_barrier(a * 3.725_290_3e-9);
        undo = 268_435_456.0;
    } else if magnitude != 0.0 && magnitude < 7.888_609e-31 {
        scaled = dd_barrier(a * 268_435_456.0);
        undo = 3.725_290_3e-9;
    }
    let c = dd_barrier(4097.0 * scaled);
    let hi = c - (c - scaled);
    let lo = scaled - hi;
    DD {
        hi: dd_barrier(hi * undo),
        lo: dd_barrier(lo * undo),
    }
}

fn two_prod_split_raw(a: f32, b: f32) -> DD {
    let hi = dd_barrier(a * b);
    let sa = split_scaled(a);
    let sb = split_scaled(b);
    let e0 = dd_barrier(dd_barrier(sa.hi * sb.hi) - hi);
    let e1 = dd_barrier(e0 + dd_barrier(sa.hi * sb.lo));
    let e2 = dd_barrier(e1 + dd_barrier(sa.lo * sb.hi));
    let lo = dd_barrier(e2 + dd_barrier(sa.lo * sb.lo));
    DD { hi, lo }
}

/// Dekker/Veltkamp split two-product, exact for finite non-overflowing products.
pub fn two_prod_split(a: f32, b: f32) -> DD {
    let sa = normalize_subnormal(a);
    let sb = normalize_subnormal(b);
    let mut aa = sa.value;
    let mut bb = sb.value;
    if sa.shifts > 0 {
        bb = dd_barrier(bb * 5.960_464_5e-8);
    }
    if sb.shifts > 0 {
        aa = dd_barrier(aa * 5.960_464_5e-8);
    }
    let result = two_prod_split_raw(aa, bb);
    if result.hi == 0.0 && result.lo == 0.0 {
        return DD::ZERO;
    }
    result
}

fn two_prod_fma_raw(a: f32, b: f32) -> DD {
    let hi = dd_barrier(a * b);
    let lo = a.mul_add(b, -hi);
    DD { hi, lo }
}

/// IEEE fused-multiply-add two-product; selected only after a GPU exactness canary.
pub fn two_prod_fma(a: f32, b: f32) -> DD {
    let sa = normalize_subnormal(a);
    let sb = normalize_subnormal(b);
    let mut aa = sa.value;
    let mut bb = sb.value;
    if sa.shifts > 0 {
        bb = dd_barrier(bb * 5.960_464_5e-8);
    }
    if sb.shifts > 0 {
        aa = dd_barrier(aa * 5.960_464_5e-8);
    }
    let result = two_prod_fma_raw(aa, bb);
    if result.hi == 0.0 && result.lo == 0.0 {
        return DD::ZERO;
    }
    result
}

pub fn two_prod(a: f32, b: f32) -> DD {
    two_prod_split(a, b)
}
