from os import PathLike
from typing import Any, Callable, Iterable, Mapping, Sequence

class CacheReport:
    hits: list[str]
    misses: list[str]
    bytes_read: int
    bytes_written: int
    wall_ms_saved: float
    @property
    def hit_rate(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

class SequenceResult:
    frame_hashes: list[str]
    frame_blobs: list[bytes]
    cache_report: CacheReport
    predicted_recompute: list[tuple[int, str]]
    observed_recompute: list[tuple[int, str]]
    elapsed_seconds: float
    @property
    def prediction_matches(self) -> bool: ...

def leaf_key(content: bytes | bytearray | memoryview) -> str: ...
def pass_key(label: str, pipeline_descriptor: bytes, uniform_bytes: bytes, input_keys: Sequence[str], capability_fingerprint_bytes: bytes, engine_fingerprint_bytes: bytes) -> str: ...
def engine_fingerprint() -> bytes: ...
def capability_fingerprint(value: Mapping[str, Any] | None = ..., *, backend: str | None = ..., dx12_compiler: str | None = ..., naga_capabilities: Sequence[str] = ...) -> bytes: ...
def render_sequence(recipe: Any, frames: Iterable[int] = ..., cache: str | PathLike[str] | None = ..., *, dry_run: bool = ..., max_bytes: int = ..., verify_reads: bool = ..., render_frame: Callable[[Mapping[str, Any], int], bytes | bytearray | memoryview] | None = ..., render_frame_fingerprint: bytes | None = ..., capabilities: Mapping[str, Any] | None = ..., reference_work_factor: int = ...) -> SequenceResult: ...
def explain(key: str, cache: str | PathLike[str] = ...) -> dict[str, Any]: ...
def gc(max_bytes: int, cache: str | PathLike[str] = ...) -> int: ...
def verify(cache: str | PathLike[str] = ...) -> dict[str, int]: ...
