from datetime import datetime

def body_position(body: str, datetime_utc: datetime, lat: float, lon: float) -> tuple[float, float, float]: ...
def moon_phase(datetime_utc: datetime, lat: float | None = None, lon: float | None = None) -> float: ...
