from __future__ import annotations
from typing import Any
import numpy as np

def compress_dem(dem: Any, eps: float, progressive: bool = ...) -> bytes: ...
def decompress_dem(data: bytes | bytearray | memoryview) -> tuple[np.ndarray, dict[str, Any]]: ...
def verify_dem(data: bytes | bytearray | memoryview, source: Any | None = ...) -> dict[str, Any]: ...
