from __future__ import annotations

import os
from typing import Any

import numpy as np


class RasterInfo:
    @property
    def path(self) -> str: ...
    @property
    def driver(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def band_count(self) -> int: ...
    @property
    def dtype_per_band(self) -> list[str]: ...
    @property
    def crs_wkt(self) -> str | None: ...
    @property
    def crs_authority(self) -> dict[str, str] | None: ...
    @property
    def transform(self) -> tuple[float, float, float, float, float, float] | None: ...
    @property
    def bounds(self) -> tuple[float, float, float, float] | None: ...
    @property
    def resolution(self) -> tuple[float, float] | None: ...
    @property
    def nodata_per_band(self) -> list[float | None]: ...
    @property
    def block_size(self) -> list[tuple[int, int]] | None: ...
    @property
    def tiling(self) -> str | None: ...
    @property
    def compression(self) -> str | None: ...
    @property
    def is_georeferenced(self) -> bool: ...
    @property
    def warnings(self) -> list[dict[str, str | None]]: ...
    def as_dict(self) -> dict[str, Any]: ...


def read_raster_info(path: os.PathLike[str] | str) -> RasterInfo: ...


def write_raster(
    path: os.PathLike[str] | str,
    array: np.ndarray,
    *,
    crs: str | dict[str, Any] | None = ...,
    transform: tuple[float, float, float, float, float, float] | None = ...,
    nodata: float | list[float] | tuple[float, ...] | None = ...,
    driver: str = ...,
    overwrite: bool = ...,
    creation_options: dict[str, Any] | None = ...,
    like_path: os.PathLike[str] | str | None = ...,
    like_info: RasterInfo | None = ...,
) -> RasterInfo:
    """Write a GeoTIFF; every 3D array is interpreted as (bands, height, width)."""
    ...
