from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Mapping, Sequence

from .diagnostics import Diagnostic, ValidationReport
from .graticule import GraticuleSpec

PathLikeStr = os.PathLike[str] | str


class TerrainSource:
    path: PathLikeStr | None
    data: Any | None
    crs: str | None
    metadata: Mapping[str, Any] | None
    elevation_sampling_available: bool
    dtype: str
    nodata_policy: str
    def __init__(self, path: PathLikeStr | None = ..., data: Any | None = ..., crs: str | None = ..., metadata: Mapping[str, Any] | None = ..., elevation_sampling_available: bool = ..., dtype: str = ..., nodata_policy: str = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class RasterOverlay:
    def __init__(self, layer_id: str, path: PathLikeStr | None = ..., crs: str | None = ..., opacity: float = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class VectorOverlay:
    def __init__(self, layer_id: str, path: PathLikeStr | None = ..., features: Sequence[Mapping[str, Any]] | None = ..., crs: str | None = ..., style: Mapping[str, Any] | None = ..., width_px: float | None = ..., width_world: float | None = ..., line_join: str = ..., line_cap: str = ..., dash_array: Sequence[float] | None = ..., style_support: Mapping[str, Any] | None = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class FontFallbackRange:
    def __init__(self, name: str, start: int, end: int, font_family: str) -> None: ...
    def covers(self, char: str) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...

class FontAtlas:
    glyphs: set[str]
    def __init__(self, glyphs: set[str] = ..., font_size: int = ..., line_height: int = ..., baseline: int = ..., coverage: Mapping[str, Any] | None = ..., source_path: str | None = ..., fallbacks: Sequence[FontFallbackRange | Mapping[str, Any]] = ..., diagnostics: Sequence[Diagnostic | Mapping[str, Any]] = ...) -> None: ...
    @classmethod
    def default_latin(cls, *, fallbacks: Sequence[FontFallbackRange | Mapping[str, Any]] | None = ...) -> FontAtlas: ...
    @classmethod
    def from_font(cls, path: str | Path, *, ranges: Sequence[FontFallbackRange | Mapping[str, Any]] | None = ..., font_size: int = ..., line_height: int | None = ...) -> FontAtlas: ...
    def covers(self, char: str) -> bool: ...
    def fallback_for(self, char: str) -> FontFallbackRange | None: ...
    def validate_text(self, text: str, *, layer_id: str | None = ..., object_id: str | None = ...) -> list[Diagnostic]: ...
    def to_dict(self) -> dict[str, Any]: ...

class TypographySettings:
    def __init__(self, font_size: int = ..., kerning: bool = ..., tracking: float = ..., line_height: float | None = ..., multiline: bool = ..., callout: bool = ..., callout_offset: Sequence[float] = ..., halo_width_px: float = ..., halo_color: Sequence[float] | str | None = ...) -> None: ...
    def measure_text(self, text: str) -> dict[str, Any]: ...
    def layout_label(self, text: str, *, anchor: Sequence[float]) -> dict[str, Any]: ...
    def to_dict(self) -> dict[str, Any]: ...

class LabelLayer:
    def __init__(self, layer_id: str, labels: Sequence[Mapping[str, Any]] | None = ..., glyph_atlas: Mapping[str, Any] | None = ..., atlas: FontAtlas | Mapping[str, Any] | None = ..., typography: Mapping[str, Any] | None = ..., occlusion: str = ..., priority_rules: Sequence[Any] | None = ..., plan: Any | None = ..., metadata: Mapping[str, Any] | None = ..., diagnostics: Sequence[Diagnostic | Mapping[str, Any]] | None = ...) -> None: ...
    @classmethod
    def from_features(cls, features: Sequence[Mapping[str, Any]], *, text: Any = ..., crs: str | None = ..., target_crs: str | None = ..., terrain_sampling: str = ..., terrain_sampler: Any | None = ..., typography: Mapping[str, Any] | None = ..., occlusion: str = ..., layer_id: str = ..., glyph_atlas: Mapping[str, Any] | None = ..., atlas: FontAtlas | Mapping[str, Any] | None = ..., metadata: Mapping[str, Any] | None = ...) -> LabelLayer: ...
    @classmethod
    def from_geodataframe(cls, gdf: Any, *, text: Any = ..., crs: str | None = ..., target_crs: str | None = ..., terrain_sampling: str = ..., terrain_sampler: Any | None = ..., typography: Mapping[str, Any] | None = ..., occlusion: str = ..., layer_id: str = ..., glyph_atlas: Mapping[str, Any] | None = ..., atlas: FontAtlas | Mapping[str, Any] | None = ..., metadata: Mapping[str, Any] | None = ...) -> LabelLayer: ...
    @classmethod
    def from_style_layer(cls, features: Sequence[Mapping[str, Any]], style_layer: Any, *, crs: str | None = ..., target_crs: str | None = ..., terrain_sampling: str = ..., terrain_sampler: Any | None = ..., occlusion: str = ..., layer_id: str = ..., glyph_atlas: Mapping[str, Any] | None = ..., atlas: FontAtlas | Mapping[str, Any] | None = ..., metadata: Mapping[str, Any] | None = ...) -> LabelLayer: ...
    def compile_labels(self, camera: Any, viewport: Any, terrain: Any | None = ...) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...

class PointCloudLayer:
    support_level: str
    def __init__(self, layer_id: str, path: PathLikeStr | None = ..., crs: str | None = ..., point_count: int | None = ..., support_level: str = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class BuildingLayer:
    def __init__(self, layer_id: str, source: str | Mapping[str, Any] | None = ..., support_level: str = ..., geometry_count: int | None = ..., bounds: Sequence[float] | None = ..., material_status: str | None = ..., features: Sequence[Mapping[str, Any]] | None = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    @classmethod
    def from_geojson(cls, path: str | Path, **options: Any) -> BuildingLayer: ...
    @classmethod
    def from_cityjson(cls, path: str | Path, **options: Any) -> BuildingLayer: ...
    @classmethod
    def from_3dtiles(cls, source: str | Mapping[str, Any], **options: Any) -> BuildingLayer: ...
    def to_dict(self) -> dict[str, Any]: ...

class Tiles3DLayer:
    def __init__(self, layer_id: str, source: str | Mapping[str, Any] | None = ..., support_level: str = ..., lod: Mapping[str, Any] | None = ..., cache_budget: int | None = ..., cache_stats: Mapping[str, Any] | None = ..., metadata: Mapping[str, Any] | None = ..., diagnostics: Sequence[Diagnostic | Mapping[str, Any]] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class MapFurnitureLayer:
    def __init__(self, title: str | None = ..., legend: Mapping[str, Any] | None = ..., scale_bar: Mapping[str, Any] | None = ..., north_arrow: Mapping[str, Any] | None = ..., graticule: GraticuleSpec | Mapping[str, Any] | None = ..., keepouts: Sequence[Any] | None = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class OrbitCamera:
    def __init__(self, target: Sequence[float] = ..., distance: float = ..., azimuth_deg: float = ..., elevation_deg: float = ..., fov_deg: float = ..., near: float | None = ..., far: float | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class LightingPreset:
    def __init__(self, name: str = ..., sun_direction: Sequence[float] | None = ..., intensity: float = ..., settings: Mapping[str, Any] | None = ..., overrides: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class OutputSpec:
    def __init__(self, width: int, height: int, format: str = ..., path: PathLikeStr | None = ..., samples: int = ..., denoiser: str = ..., aovs: Sequence[str] = ..., hdr: bool = ..., bit_depth: int = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class ReproducibilityProfile:
    def __init__(self, seed: int = ..., camera: Mapping[str, Any] | None = ..., output_size: Sequence[int] | None = ..., terrain_transform: Mapping[str, Any] | None = ..., style_hashes: Mapping[str, str] | None = ..., asset_hashes_or_ids: Mapping[str, str] | None = ..., renderer_backend: str | None = ..., pixel_tolerance: float | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SceneRecipe:
    def __init__(self, terrain: TerrainSource, camera: OrbitCamera, lighting: LightingPreset, layers: Sequence[Any] = ..., output: OutputSpec | None = ..., target_crs: str | None = ..., map_furniture: MapFurnitureLayer | None = ..., render_policy: str = ..., diagnostics_policy: Mapping[str, Any] | None = ..., reproducibility_profile: ReproducibilityProfile | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class MapSceneNativeUnavailable(RuntimeError):
    diagnostics: list[dict[str, Any]]
    diagnostic: dict[str, Any] | None
    def __init__(self, blocks: Mapping[str, Any] | Sequence[Mapping[str, Any]]) -> None: ...

class MapSceneTextLayoutError(RuntimeError):
    diagnostics: list[dict[str, Any]]
    diagnostic: dict[str, Any]
    def __init__(self, diagnostic: Mapping[str, Any]) -> None: ...

class CompiledScenePlan:
    recipe_hash: str
    camera_terrain_key: str
    label_plans: Mapping[str, Any]
    manifest: Any
    validation_report: ValidationReport
    def __init__(self, recipe_hash: str, camera_terrain_key: str, label_plans: Mapping[str, Any], manifest: Any, validation_report: ValidationReport) -> None: ...

class MapScene:
    recipe: SceneRecipe
    last_render_path: str | None
    last_render_backend: str | None
    last_render_metadata: dict[str, Any] | None
    compiled_label_plans: dict[str, Any]
    compiled_plan: CompiledScenePlan | None
    def __init__(self, recipe: SceneRecipe | None = ..., *, terrain: TerrainSource | None = ..., camera: OrbitCamera | None = ..., lighting: LightingPreset | None = ..., layers: Sequence[Any] | None = ..., output: OutputSpec | None = ..., target_crs: str | None = ..., map_furniture: MapFurnitureLayer | None = ..., render_policy: str = ..., diagnostics_policy: Mapping[str, Any] | None = ..., reproducibility_profile: ReproducibilityProfile | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def alignment_report(self) -> dict[str, Any]: ...
    def material_vt_stats(self) -> dict[str, float] | None: ...
    @classmethod
    def load_bundle(cls, path: str | Path) -> MapScene: ...
    def validate(self) -> ValidationReport: ...
    def compile_plan(self) -> CompiledScenePlan: ...
    def render(
        self,
        path: str | None = ...,
        *,
        emit_provenance: bool = ...,
        provenance_signing_key: bytes | None = ...,
    ) -> ValidationReport: ...
    def save_bundle(self, path: str | Path) -> ValidationReport: ...

__all__: list[str]
