# python/forge3d/path_tracing.pyi
# Type stubs for path tracing API skeleton (Workstream A).
# This exists to keep the package typed and IDE-friendly.
# RELEVANT FILES:python/forge3d/path_tracing.py,python/forge3d/__init__.pyi,tests/test_path_tracing_api.py

from __future__ import annotations
from typing import Tuple
import numpy as np

class PathTracer:
    def __init__(self, width: int, height: int, *, max_bounces: int = ..., seed: int = ...) -> None: ...
    @property
    def size(self) -> Tuple[int, int]: ...
    def render_rgba(self, *, spp: int = ...) -> np.ndarray: ...
    def add_sphere(self, center: tuple[float, float, float], radius: float, material_or_color) -> None: ...
    def add_triangle(self, v0: tuple[float, float, float], v1: tuple[float, float, float], v2: tuple[float, float, float], material_or_color) -> None: ...

def create_path_tracer(width: int, height: int, *, max_bounces: int = ..., seed: int = ...) -> PathTracer: ...
def _fresnel_schlick(cos_theta: np.ndarray, F0: np.ndarray) -> np.ndarray: ...
