from typing import Any

def dd_selftest() -> dict[str, Any]: ...
def dd_harness(operation: str, n: int = 100_000_000) -> dict[str, Any]: ...
def dd_jitter_demo(frames: int = 1_000) -> dict[str, Any]: ...
