from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

__all__: list[str]

def recipe_manifest(value: Any, *, golden_fixture_intent: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...

@dataclass
class RecipeInput:
    name: str
    kind: str
    crs: str | None = ...
    shape: Any | None = ...
    format: str | None = ...
    role: str | None = ...

@dataclass
class RecipeOutput:
    kind: str
    format: str
    path: str | None = ...
    deterministic: bool | None = ...

@dataclass
class RecipeLayer:
    layer_id: str
    layer_type: str
    role: str
    required: bool
    style_ref: str | None = ...

@dataclass
class SourceEvidence:
    path: str
    line_start: int | None = ...
    line_end: int | None = ...
    note: str | None = ...

@dataclass
class GoldenFixtureIntent:
    status: str
    source_test: str | None = ...
    source_file: str | None = ...
    note: str | None = ...

@dataclass
class RecipeManifest:
    schema_version: str = ...
    recipe_family: str = ...
    recipe_id: str = ...
    status: str = ...
    source_examples: Sequence[str] = ...
    source_evidence: Sequence[SourceEvidence | Mapping[str, Any]] = ...
    required_inputs: Sequence[RecipeInput | Mapping[str, Any]] = ...
    optional_inputs: Sequence[RecipeInput | Mapping[str, Any]] = ...
    produced_outputs: Sequence[RecipeOutput | Mapping[str, Any]] = ...
    layers: Sequence[RecipeLayer | Mapping[str, Any]] = ...
    alignment: Mapping[str, Any] = ...
    preprocessing: Mapping[str, Any] = ...
    camera_defaults: Mapping[str, Any] = ...
    lighting_defaults: Mapping[str, Any] = ...
    styling_defaults: Mapping[str, Any] = ...
    annotations_defaults: Mapping[str, Any] = ...
    render_export_defaults: Mapping[str, Any] = ...
    support_status: Mapping[str, str] = ...
    diagnostics: Sequence[str] = ...
    tests: Sequence[str] = ...
    golden_fixture_intent: GoldenFixtureIntent | Mapping[str, Any] = ...
    non_goals: Sequence[str] = ...
    open_questions: Sequence[str] = ...

def manifest_from_dict(data: Mapping[str, Any]) -> RecipeManifest: ...
def manifest_to_dict(manifest: RecipeManifest) -> dict[str, Any]: ...
def manifest_to_json(manifest: RecipeManifest) -> str: ...
def manifest_from_json(text: str) -> RecipeManifest: ...
def validate_manifest(
    manifest: RecipeManifest | Mapping[str, Any],
    *,
    repo_root: str | Path | None = ...,
) -> list[str]: ...
def load_manifest(path: str | Path) -> RecipeManifest: ...
def save_manifest(manifest: RecipeManifest, path: str | Path) -> None: ...
