from typing import Any, Mapping, Sequence
from dataclasses import dataclass

@dataclass(frozen=True)
class RenderPassInput:
    data: Any
    color_space: str
    alpha_mode: str
    def __init__(self, data: Any, color_space: str = ..., alpha_mode: str = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __hash__(self) -> int: ...
    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> RenderPassInput: ...

@dataclass(frozen=True)
class RenderPassSpec:
    name: str
    kind: str
    inputs: Sequence[str]
    operation: str
    parameters: Mapping[str, float]
    color_space: str
    def __init__(self, name: str, kind: str, inputs: Sequence[str], operation: str = ..., parameters: Mapping[str, float] = ..., color_space: str = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __hash__(self) -> int: ...
    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> RenderPassSpec: ...

def compile_passes(passes: Sequence[RenderPassSpec], inputs: Mapping[str, RenderPassInput], shape: tuple[int, int], *, include_data: bool = ...) -> dict[str, Any]: ...
def decode_passes(payload: Mapping[str, Any], snapshots: Mapping[str, RenderPassInput] | None = ...) -> tuple[tuple[RenderPassSpec, ...], dict[str, RenderPassInput]]: ...
def execute_passes(compiled_json: str, shape: tuple[int, int], snapshots: Mapping[str, RenderPassInput] | None = ...) -> Any: ...
