// Generated by scripts/generate_dd.py from scripts/dd_vector.rs.in.
use super::*;

#[allow(dead_code)] // Wired into the DD vertex path in DUPLA Task 3.
pub fn dd_dot3(a: DDVec3, b: DDVec3) -> DD {
    dd_add(dd_add(dd_mul(a.x, b.x), dd_mul(a.y, b.y)), dd_mul(a.z, b.z))
}

#[allow(dead_code)] // Wired into the DD vertex path in DUPLA Task 3.
pub fn dd_length3(value: DDVec3) -> DD {
    dd_sqrt(dd_dot3(value, value))
}

pub fn dd_sub_vec3(a: DDVec3, b: DDVec3) -> DDVec3 {
    DDVec3 {
        x: dd_sub(a.x, b.x),
        y: dd_sub(a.y, b.y),
        z: dd_sub(a.z, b.z),
    }
}
